### ISSUE TITLE
Please, clarify the license

### ISSUE THREAD

**Issue by rkrasin** [fogleman/slicer#1]
Hello Michael,

can you please add a LICENSE file on the top of the repository, so that the licensing terms are clear? My suggestion would be to use one of the permissive licenses, such as [MIT](https://opensource.org/licenses/MIT), [BSD](https://opensource.org/licenses/BSD-2-Clause) or [Apache 2](https://opensource.org/licenses/Apache-2.0), but it's certainly up to you as the author.

Thank you in advance!

**Comment by fogleman** [comment]
Done.

**Comment by rkrasin** [comment]
Awesome, thank you!
